<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>data-wrangling.knit</title>

<script src="site_libs/header-attrs-2.17/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="site_libs/datatables-binding-0.26/datatables.js"></script>
<link href="site_libs/dt-core-1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="site_libs/dt-core-1.12.1/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="site_libs/dt-core-1.12.1/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">ChemStat-R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="getting-started-with-r.html">Getting Started with R</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Essential of The R Language
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="essential-of-r-language.html">Table of Content</a>
    </li>
    <li>
      <a href="intoduction-to-use-r.html">Introduction to Using R</a>
    </li>
    <li>
      <a href="r-data-input-and-type.html">Importing/Exporting  Data into R</a>
    </li>
    <li>
      <a href="data-wrangling.html">Data Wrangling with R</a>
    </li>
    <li>
      <a href="mathematics-with-r.html">Simple Mathematics with R</a>
    </li>
    <li>
      <a href="basic-statistics-with-r.html">Basic Statistics with R</a>
    </li>
    <li>
      <a href="multivariate-statistics.html">Mltivariate Statistics with R</a>
    </li>
    <li>
      <a href="data-visualization.html">Data Visualization with R</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Curve Fitting with R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="curve-fitting-with-r.html">Table of Content</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Cheminformatics with R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="cheminformatics-with-r.html">Table of Content</a>
    </li>
    <li>
      <a href="getting-strated-chem.html">Getting Started</a>
    </li>
    <li>
      <a href="cheminformatics-with-chemminer.html">Cheminformatics with ChemmineR</a>
    </li>
    <li>
      <a href="cheminformatics-with-cdk.html">Cheminformatics with CDK</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    ICP-MS Data Processing with R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="icp-ms-data-processing-and-analysis-with-r.html">Table of Content</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:zia207@gmail.com">
    <span class="fa fa-envelope fa-lg"></span>
     
    Email
  </a>
</li>
<li>
  <a href="http://github.com/zia207">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/zia-ahmed-a7653578">
    <span class="fa fa-linkedin fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<div style="margin-bottom:50px;">

</div>
<p><img src="Image/PNG_FILE_02/data_wragling.png" width="100%" style="display: block; margin: auto;" /></p>
<div style="margin-bottom:20px;">

</div>
<div id="table-of-content" class="section level3">
<h3><strong>Table of Content</strong></h3>
<ul>
<li><p><a href="#data-wrangling">Data Wrangling</a></p></li>
<li><p><a href="#important-r-rackages-for-data-wrangling">Important R
Packages for Data Wrangling</a></p></li>
<li><p><a href="#data-processing-with-dplyr-tidyr">Data Processing with
dplyr and tidyr</a></p>
<ul>
<li><p><a href="#Pipe-Operator">Pipe Operator</a></p></li>
<li><p><a href="#jOIN">Join</a></p></li>
<li><p><a href="#filter">Filter</a></p></li>
<li><p><a href="#select">Select</a></p></li>
<li><p><a href="#rename">Rename</a></p></li>
<li><p><a href="#arrange">Arrange</a></p></li>
<li><p><a href="#combined-multiple-functions-with-pipes">Combined
multiple functions with Pipes</a></p></li>
<li><p><a href="#pivoting-dataframe">Pivoting dataframe</a></p></li>
<li><p><a href="(#mutate)">Mutate</a></p></li>
<li><p><a href="#summarize">summarize</a></p></li>
<li><p><a href="#group-by">Group by</a></p></li>
</ul></li>
<li><p><a href="#cleaning-a-messy-data">Cleaning a Messy
Data</a></p></li>
<li><p><a href="#further-reading">Further Reading</a></p></li>
</ul>
<div style="margin-bottom:60px;">

</div>
</div>
<div id="data-wrangling" class="section level2">
<h2><strong>Data Wrangling</strong></h2>
<p><strong>Data wrangling</strong>, also known as <strong>data
munging</strong>, is a series of assembling, cleaning, and transforming
processes to understand data better and make them more accessible and
easier to analyze. Due to the availability of a large amount of data
from different sources with different formats, data wrangling has become
an essential part of data modeling which helps data scientists fasten
the decision-making process.</p>
<p>Here below <a href="https://favtutor.com/blogs/data-wrangling">6
steps data wrangling</a>:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Discovering</strong>: The first step in data wrangling is
analyzing the data before imputing the data. Wrangling needs to be done
in a systematic fashion, based on some criteria which could demarcate
and divide the data accordingly – these are identified in this
step.</p></li>
<li><p><strong>Structuring</strong>: In most cases, the raw data
extracted as user information generally doesn’t have structured data.
The data should be restructured in a fashion that better suits the
analytical method used. Based on the category identified in the first
step, the data should be segregated to make use easier. For better
analysis we have to select one column that may become two or rows may be
split, this is also called feature engineering.</p></li>
<li><p><strong>Cleaning</strong>: Processed datasets definitely have
some outliers, which can skew the results of the analysis. The dataset
should be cleaned for optimum results. In this step, the data is cleaned
thoroughly for high-quality data analysis. Null values should be
imputed, and the formatting will be standardized to create higher
quality processed data</p></li>
<li><p><strong>Enriching</strong>: After processing the data, it will
have to be enriched – this is performed in the fourth step. This implies
that you one has to take stock of what is in the data and strategize
whether you have upscale, downsample, or perform data augmentation.
There are different methods to resample the data, one downsampling the
data, and the other creating synthetic data using upsampling.</p></li>
<li><p><strong>Validating</strong>: Validation refers to iterative
programming steps that are used to verify the consistency and the
quality of data after processing. For example, you will have to
ascertain whether the fields in the data set are accurate via validating
data, or checking whether the attributes are normally
distributed.</p></li>
<li><p><strong>Publishing</strong>: The processed and wrangled data is
published so that it can be used further – which is the sole purpose of
data wrangling. If needed, the complete data wrangling process should be
documented efficiently for the users and clients for easy
usage.</p></li>
</ol>
<div style="margin-bottom:20px;">

</div>
<p><img src="Image/PNG_FILE_02/data_wrangling_background.png" width="100%" style="display: block; margin: auto;" /></p>
<div style="margin-bottom:20px;">

</div>
</div>
<div id="important-r-packages-for-data-wrangling"
class="section level2">
<h2><strong>Important R Packages for Data Wrangling</strong></h2>
<ul>
<li><p><a
href="https://dplyr.tidyverse.org/index.html">dplyr</a></p></li>
<li><p><a href="https://purrr.tidyverse.org/">purr</a></p></li>
<li><p><a href="https://tidyr.tidyverse.org/">tidyr</a></p></li>
<li><p><a href="https://lubridate.tidyverse.org/">lubridate</a></p></li>
<li><p><a href="https://magrittr.tidyverse.org/">magrittr</a></p></li>
<li><p><a href="http://plyr.had.co.nz/">plyr</a></p></li>
<li><p><a
href="https://cran.r-project.org/web/packages/purrrlyr/index.html">purrrlyr</a></p></li>
<li><p><a
href="https://rdatatable.gitlab.io/data.table/">data.table</a></p></li>
<li><p><a
href="https://cran.r-project.org/web/packages/sqldf/index.html">sqldf</a></p></li>
<li><p><a
href="https://www.tidyverse.org/blog/2019/11/dtplyr-1-0-0/">dtplyr</a></p></li>
<li><p><a href="https://rstudio.github.io/DT/">DT</a></p></li>
</ul>
<p><a href="https://dplyr.tidyverse.org/index.html">dplyr</a>, <a
href="https://purrr.tidyverse.org/">purr</a>, <a
href="https://tidyr.tidyverse.org/">tidyr</a>, <a
href="https://lubridate.tidyverse.org/">lubridate</a>, and <a
href="https://magrittr.tidyverse.org/">magrittr</a> are installed with
<a href="https://www.tidyverse.org/packages/">tidyverse</a> package as
discussed before.</p>
<div style="margin-bottom:20px;">

</div>
</div>
<div id="data-processing-with-dplyr-and-tidyr" class="section level2">
<h2><strong>Data Processing with dplyr and tidyr</strong></h2>
<p>The <strong>dplyr</strong> and <strong>tidyr</strong> are the most
commonly use data manipulation packages, providing a set of functions
that help us solve the most common data manipulation challenges. These
are:</p>
<ul>
<li><p><strong>mutate()</strong> adds new variables that are functions
of existing variables</p></li>
<li><p><strong>select()</strong> picks variables based on their
names.</p></li>
<li><p><strong>filter()</strong> picks cases based on their
values.</p></li>
<li><p><strong>summarise()</strong> reduces multiple values down to a
single summary.</p></li>
<li><p><strong>arrange()</strong> changes the ordering of the
rows.</p></li>
<li><p><strong>join()</strong> join two data-frames</p></li>
<li><p><strong>group_by()</strong> All above combine naturally with
group_by() which allows you to perform any operation “by
group”.</p></li>
</ul>
<div style="margin-bottom:40px;">

</div>
<p>Here below data Wrangling with <a
href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">dplyr
and tidyr Cheat Sheets</a>:</p>
<div style="margin-bottom:20px;">

</div>
<p><img src="Image/PNG_FILE_02/data_wragling%20cheat_sheet_01.png" width="100%" style="display: block; margin: auto;" /></p>
<img src="Image/PNG_FILE_02/data_wragling%20cheat_sheet_02.png" width="100%" style="display: block; margin: auto;" />
<div style="margin-bottom:20px;">

</div>
<div id="load-package" class="section level3">
<h3><strong>Load Package</strong></h3>
<pre class="r"><code>library(tidyverse)
library(data.table)
library(DT)
#require(plyr)
# library(dplyr)
# library(readr)</code></pre>
<div style="margin-bottom:20px;">

</div>
</div>
<div id="load-data" class="section level3">
<h3><strong>Load data</strong></h3>
<p>In this exercise we will use two data sets: USA county level lung
cancer mortality rates with risk factors from 1998 t0 2012 and USA
County FIPS Codes. We will use <strong>read_csv()</strong> function of
<strong>readr</strong> package to import data a <strong>Tidy</strong>
data.</p>
<pre class="r"><code>## Create a data folder
dataFolder&lt;-&quot;E:/Dropbox/GitHub/chemstat-r-github.io/Data/&quot;
df&lt;-read_csv(paste0(dataFolder,&quot;LBC_data.csv&quot;))
fips&lt;-read_csv(paste0(dataFolder, &quot;US_FIPS.csv&quot;))
regions&lt;-read_csv(paste0(dataFolder, &quot;US_regions.csv&quot;))</code></pre>
<div style="margin-bottom:20px;">

</div>
<p>We examine structure of the data:</p>
<pre class="r"><code>str(df); </code></pre>
<pre><code>## spc_tbl_ [46,605 × 8] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ FIPS    : num [1:46605] 1001 1001 1001 1001 1001 ...
##  $ Year    : num [1:46605] 1998 1999 2000 2001 2002 ...
##  $ SMOKING : num [1:46605] 27 26 26 26.5 26.6 26.3 27.1 26.4 26.3 25.6 ...
##  $ POVERTY : num [1:46605] 11.3 11.4 10.5 10.8 10.3 10.4 11.6 10.4 12.5 10.4 ...
##  $ PM25    : num [1:46605] 17.1 15.4 14 13.9 14.8 ...
##  $ NO2     : num [1:46605] 1.38 1.04 1.47 1.74 1.1 0.9 1.1 1.17 0.84 0.77 ...
##  $ SO2     : num [1:46605] 0.057 0.055 0.054 0.051 0.052 0.053 0.05 0.055 0.055 0.056 ...
##  $ LBC_RATE: num [1:46605] 90.6 90.4 89.5 89.3 89.2 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   FIPS = col_double(),
##   ..   Year = col_double(),
##   ..   SMOKING = col_double(),
##   ..   POVERTY = col_double(),
##   ..   PM25 = col_double(),
##   ..   NO2 = col_double(),
##   ..   SO2 = col_double(),
##   ..   LBC_RATE = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<div style="margin-bottom:20px;">

</div>
<p>take a <strong>glimpse</strong> of the df dataset:</p>
<pre class="r"><code>glimpse(df)</code></pre>
<pre><code>## Rows: 46,605
## Columns: 8
## $ FIPS     &lt;dbl&gt; 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1…
## $ Year     &lt;dbl&gt; 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2…
## $ SMOKING  &lt;dbl&gt; 27.0, 26.0, 26.0, 26.5, 26.6, 26.3, 27.1, 26.4, 26.3, 25.6, 2…
## $ POVERTY  &lt;dbl&gt; 11.3, 11.4, 10.5, 10.8, 10.3, 10.4, 11.6, 10.4, 12.5, 10.4, 1…
## $ PM25     &lt;dbl&gt; 17.08, 15.38, 14.04, 13.87, 14.85, 13.88, 12.61, 12.59, 12.92…
## $ NO2      &lt;dbl&gt; 1.38, 1.04, 1.47, 1.74, 1.10, 0.90, 1.10, 1.17, 0.84, 0.77, 0…
## $ SO2      &lt;dbl&gt; 0.057, 0.055, 0.054, 0.051, 0.052, 0.053, 0.050, 0.055, 0.055…
## $ LBC_RATE &lt;dbl&gt; 90.63, 90.39, 89.47, 89.30, 89.15, 87.26, 84.98, 85.56, 84.34…</code></pre>
</div>
<div id="pipe-operator" class="section level3">
<h3><strong>Pipe Operator</strong></h3>
<p>Before starting this tutorial, I like to brief you about the
<strong>Pipe Operator</strong>. This is the most important operator for
data wrangling in R. The pipe operator, written as
<strong>%&gt;%</strong>, has been a longstanding feature of the
<strong>magrittr</strong> package for R. It takes the output of one
function and passes it into another function as an argument. This allows
us to link a sequence of analysis steps. In this tutorial, you can see
exactly how this works in a real example. (Source:<a
href="https://towardsdatascience.com/an-introduction-to-the-pipe-in-r-823090760d64"
class="uri">https://towardsdatascience.com/an-introduction-to-the-pipe-in-r-823090760d64</a>)</p>
</div>
</div>
<div id="section" class="section level1">
<h1></h1>
<div id="join" class="section level2">
<h2><strong>Join</strong></h2>
<p>In R we use <strong>base::merge()</strong> function to merge two
dataframes. This function is present inside <strong>join()</strong>
function of dplyr package. The most important condition for joining two
dataframes is that the column type should be the same of “key” variable
by the merging happens. Types of <strong>base::merge()</strong> and
<strong>join()</strong> function of dplyr available in R are:</p>
<img src="Image/PNG_FILE_02/join_functions.png" width="100%" style="display: block; margin: auto;" />
<div style="margin-bottom:20px;">

</div>
<p>The advantages of the specific dplyr verbs is that they It automatic
identify the common “key” columns of two data-frames. dplyr’s joins are
considerably faster and don’t mess with the order of the rows. (source:
<a href="https://r4ds.had.co.nz/relational-data.html"
class="uri">https://r4ds.had.co.nz/relational-data.html</a>) .</p>
<p>First we will join fips and regions file using <em>inner_join</em>()*
and then join df files.</p>
<pre class="r"><code>fips_df = inner_join(fips, regions)</code></pre>
<pre><code>## Joining, by = &quot;STATE&quot;</code></pre>
<pre class="r"><code>head(fips_df)</code></pre>
<pre><code>## # A tibble: 6 × 7
##    FIPS STATE   COUNTY               X        Y REGION DIVISION          
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;             
## 1  1001 Alabama Autauga County 872679. 1094433. South  East South Central
## 2  1003 Alabama Baldwin County 789778.  884557. South  East South Central
## 3  1005 Alabama Barbour County 997211. 1033024. South  East South Central
## 4  1007 Alabama Bibb County    822862. 1141554. South  East South Central
## 5  1009 Alabama Blount County  863725. 1255735. South  East South Central
## 6  1011 Alabama Bullock County 964067. 1055199. South  East South Central</code></pre>
<pre class="r"><code>mf = inner_join(fips_df, df)</code></pre>
<pre><code>## Joining, by = &quot;FIPS&quot;</code></pre>
<pre class="r"><code>head(mf)</code></pre>
<pre><code>## # A tibble: 6 × 14
##    FIPS STATE   COUNTY       X      Y REGION DIVIS…¹  Year SMOKING POVERTY  PM25
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1  1001 Alabama Autaug… 8.73e5 1.09e6 South  East S…  1998    27      11.3  17.1
## 2  1001 Alabama Autaug… 8.73e5 1.09e6 South  East S…  1999    26      11.4  15.4
## 3  1001 Alabama Autaug… 8.73e5 1.09e6 South  East S…  2000    26      10.5  14.0
## 4  1001 Alabama Autaug… 8.73e5 1.09e6 South  East S…  2001    26.5    10.8  13.9
## 5  1001 Alabama Autaug… 8.73e5 1.09e6 South  East S…  2002    26.6    10.3  14.8
## 6  1001 Alabama Autaug… 8.73e5 1.09e6 South  East S…  2003    26.3    10.4  13.9
## # … with 3 more variables: NO2 &lt;dbl&gt;, SO2 &lt;dbl&gt;, LBC_RATE &lt;dbl&gt;, and
## #   abbreviated variable name ¹​DIVISION</code></pre>
<p>Now we will move REGION, DIVISION column after FIPS for organizing
the columns in the following order: FIPS, REGION, DIVISION, STATE,
COUNTY, X, Y, Year, SMOKING, POVERTY, PM25, NO2, SO2, LBC_RATE. We will
use <strong>relocate()</strong> function:</p>
<pre class="r"><code>mf&lt;-relocate(mf, REGION,   DIVISION, .after = FIPS)
head(mf)</code></pre>
<pre><code>## # A tibble: 6 × 14
##    FIPS REGION DIVISION   STATE COUNTY      X      Y  Year SMOKING POVERTY  PM25
##   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  1998    27      11.3  17.1
## 2  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  1999    26      11.4  15.4
## 3  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2000    26      10.5  14.0
## 4  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2001    26.5    10.8  13.9
## 5  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2002    26.6    10.3  14.8
## 6  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2003    26.3    10.4  13.9
## # … with 3 more variables: NO2 &lt;dbl&gt;, SO2 &lt;dbl&gt;, LBC_RATE &lt;dbl&gt;</code></pre>
<p>Now explore regions names with <strong>levels()</strong></p>
<pre class="r"><code>levels(as.factor(mf$REGION))</code></pre>
<pre><code>## [1] &quot;Midwest&quot;   &quot;Northeast&quot; &quot;South&quot;     &quot;West&quot;</code></pre>
<div style="margin-bottom:20px;">

</div>
<div id="filter" class="section level3">
<h3><strong>Filter</strong></h3>
<p>The <strong>filter()</strong> function is used to subset a data
frame, retaining all rows that satisfy your conditions. To be retained,
the row must produce a value of TRUE for all conditions. Note that when
a condition evaluates to NA the row will be dropped, unlike base
subsetting with</p>
<p>There are many functions and operators that are useful when
constructing the expressions used to filter the data:</p>
<ul>
<li><p>==, &gt;, &gt;= etc</p></li>
<li><p>&amp;, |, !, xor()</p></li>
<li><p>is.na()</p></li>
<li><p>between(), near()</p></li>
</ul>
<p>We will use <strong>filter()</strong> to extract data only for
northeast (single criteria)</p>
<pre class="r"><code>mf.northeast&lt;-mf %&gt;% filter(REGION == &quot;Northeast&quot;)
levels(as.factor(mf.northeast$REGION))</code></pre>
<pre><code>## [1] &quot;Northeast&quot;</code></pre>
<p>Filtering by multiple criteria within a single logical expression -
select both Northeast and Midwest</p>
<pre class="r"><code>mf.north_mid_01&lt;- mf %&gt;% filter(REGION %in%c(&quot;Northeast&quot;,&quot;Midwest&quot;))
levels(as.factor(mf.north_mid_01$REGION))</code></pre>
<pre><code>## [1] &quot;Midwest&quot;   &quot;Northeast&quot;</code></pre>
<p>or we can use <strong>|</strong> which represents <strong>OR</strong>
in the logical condition, any of the two conditions.</p>
<pre class="r"><code>mf.north_mid_02&lt;- mf %&gt;% filter(REGION == &quot;Northeast&quot; | REGION == &quot;Midwest&quot;)
levels(as.factor(mf.north_mid_02$REGION))</code></pre>
<pre><code>## [1] &quot;Midwest&quot;   &quot;Northeast&quot;</code></pre>
<p>Following filter create a files for the Northeast region only with NY
state.</p>
<pre class="r"><code>mf.ny&lt;-mf %&gt;% filter(REGION == &quot;Northeast&quot; &amp; STATE == &quot;New York&quot;)</code></pre>
<p>Following filters will select counties rows where
<code>LBC_RATE</code> is greater than the global average of LBC -
rate:</p>
<pre class="r"><code>mean.LBC &lt;- mf %&gt;% filter(LBC_RATE &gt; mean(LBC_RATE, na.rm = TRUE))</code></pre>
<p>We will <strong>&amp;</strong> in the following filters to select
counties or rows where <code>LBC_RATE</code> is greater than the global
average of for the year 2012</p>
<pre class="r"><code>mean.LBC.2012 &lt;- mf %&gt;% filter(LBC_RATE &gt; mean(LBC_RATE, na.rm = TRUE) &amp; Year ==2012)</code></pre>
<p>Following command will select counties start with “A”. filter() with
<strong>grepl()</strong> is used to search for pattern matching.</p>
<pre class="r"><code>counties.a &lt;- mf %&gt;% filter(grepl(&quot;^A&quot;, COUNTY))
head(counties.a)</code></pre>
<pre><code>## # A tibble: 6 × 14
##    FIPS REGION DIVISION   STATE COUNTY      X      Y  Year SMOKING POVERTY  PM25
##   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  1998    27      11.3  17.1
## 2  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  1999    26      11.4  15.4
## 3  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2000    26      10.5  14.0
## 4  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2001    26.5    10.8  13.9
## 5  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2002    26.6    10.3  14.8
## 6  1001 South  East Sout… Alab… Autau… 8.73e5 1.09e6  2003    26.3    10.4  13.9
## # … with 3 more variables: NO2 &lt;dbl&gt;, SO2 &lt;dbl&gt;, LBC_RATE &lt;dbl&gt;</code></pre>
<div style="margin-bottom:20px;">

</div>
</div>
<div id="select" class="section level3">
<h3><strong>select</strong></h3>
<p><strong>dplyr</strong> selections implement a dialect of R where
operators make it easy to select variable</p>
<ul>
<li><p><strong>:</strong> for selecting a range of consecutive
variables.</p></li>
<li><p><strong>!</strong> for taking the complement of a set of
variables.</p></li>
<li><p><strong>&amp;</strong> and <strong>|</strong> for selecting the
intersection or the union of two sets of variables.</p></li>
<li><p><strong>c()</strong> for combining selections.</p></li>
</ul>
<div id="selecting-variables-or-columns" class="section level4">
<h4>Selecting Variables (or Columns)</h4>
<p>Following will create a dataframe with FIPS, Year and LBC rate</p>
<pre class="r"><code>LBC.df &lt;- mf %&gt;% select(FIPS, Year, LBC_RATE)
head(LBC.df)</code></pre>
<pre><code>## # A tibble: 6 × 3
##    FIPS  Year LBC_RATE
##   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1  1001  1998     90.6
## 2  1001  1999     90.4
## 3  1001  2000     89.5
## 4  1001  2001     89.3
## 5  1001  2002     89.2
## 6  1001  2003     87.3</code></pre>
<p>Following will create a dataframe with FIPS, Year all risk factors
(SMOKING, POVERTY, PM25, NO2, SO2)</p>
<pre class="r"><code>riskfactors.df &lt;- mf %&gt;%  select(FIPS, Year, SMOKING:SO2)
head(riskfactors.df)</code></pre>
<pre><code>## # A tibble: 6 × 7
##    FIPS  Year SMOKING POVERTY  PM25   NO2   SO2
##   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1001  1998    27      11.3  17.1  1.38 0.057
## 2  1001  1999    26      11.4  15.4  1.04 0.055
## 3  1001  2000    26      10.5  14.0  1.47 0.054
## 4  1001  2001    26.5    10.8  13.9  1.74 0.051
## 5  1001  2002    26.6    10.3  14.8  1.1  0.052
## 6  1001  2003    26.3    10.4  13.9  0.9  0.053</code></pre>
<p>Following command will give same output. The minus sign before a
variable tells R to drop the variable or variables.
<strong>-(REGION:Y)</strong>, <strong>-LBC_RATE</strong> will drop these
columns: REGION, DIVISION, STATE, COUNTY, X, Y and LBC_RATE.</p>
<pre class="r"><code>riskfactors_01.df= mf %&gt;% select(-(REGION:Y), -LBC_RATE)
head(riskfactors_01.df)</code></pre>
<pre><code>## # A tibble: 6 × 7
##    FIPS  Year SMOKING POVERTY  PM25   NO2   SO2
##   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1001  1998    27      11.3  17.1  1.38 0.057
## 2  1001  1999    26      11.4  15.4  1.04 0.055
## 3  1001  2000    26      10.5  14.0  1.47 0.054
## 4  1001  2001    26.5    10.8  13.9  1.74 0.051
## 5  1001  2002    26.6    10.3  14.8  1.1  0.052
## 6  1001  2003    26.3    10.4  13.9  0.9  0.053</code></pre>
<p>The following functions helps you to select variables based on their
names.</p>
<img src="Image/PNG_FILE_02/select.png" width="80%" style="display: block; margin: auto;" />
<div style="margin-bottom:20px;">

</div>
</div>
<div id="rename" class="section level4">
<h4><strong>Rename</strong></h4>
<p>The rename function can be used to rename variables.</p>
<pre class="r"><code>mf.new &lt;- mf %&gt;% 
        rename(&quot;LBC_Mortality_Rate&quot; = &quot;LBC_RATE&quot;)
names(mf.new)</code></pre>
<pre><code>##  [1] &quot;FIPS&quot;               &quot;REGION&quot;             &quot;DIVISION&quot;          
##  [4] &quot;STATE&quot;              &quot;COUNTY&quot;             &quot;X&quot;                 
##  [7] &quot;Y&quot;                  &quot;Year&quot;               &quot;SMOKING&quot;           
## [10] &quot;POVERTY&quot;            &quot;PM25&quot;               &quot;NO2&quot;               
## [13] &quot;SO2&quot;                &quot;LBC_Mortality_Rate&quot;</code></pre>
<div style="margin-bottom:20px;">

</div>
</div>
</div>
<div id="arrange" class="section level3">
<h3><strong>Arrange</strong></h3>
<p><strong>arrange()</strong> orders the rows of a data frame by the
values of selected columns.</p>
<pre class="r"><code># arrange ascending order as default
mf.arrange.ac&lt;- mf %&gt;% arrange(SMOKING) 
head(mf.arrange.ac$SMOKING)</code></pre>
<pre><code>## [1] 7.1 7.7 7.8 7.9 8.0 8.5</code></pre>
<pre class="r"><code># arrange descending order
mf.arrange.de&lt;- mf %&gt;% arrange(desc(SMOKING)) 
head(mf.arrange.de$SMOKING)</code></pre>
<pre><code>## [1] 44.0 42.8 42.4 42.1 41.6 41.5</code></pre>
</div>
<div id="combined-multiple-functions-with-pipes" class="section level3">
<h3><strong>Combined multiple functions with Pipes</strong></h3>
<p>In this exercise will use <strong>select()</strong>,
<em>filter()</em> and <strong>rename()</strong> in a single commands
with <strong>%&gt;%</strong>. First we select data FIPS, SATE, LBC rate
and then filter out the data NY state data for the year 2012 and then
rename LBC_RATE column.</p>
<pre class="r"><code>LBC.NY &lt;- mf %&gt;% select(FIPS, Year, STATE, LBC_RATE) %&gt;%
                 filter (STATE==&quot;New York&quot;, Year == 2012)  %&gt;%
                 rename(&quot;LBC Mortality Rate&quot;= LBC_RATE)
                 
head(LBC.NY)        </code></pre>
<pre><code>## # A tibble: 6 × 4
##    FIPS  Year STATE    `LBC Mortality Rate`
##   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                   &lt;dbl&gt;
## 1 36001  2012 New York                 57.9
## 2 36003  2012 New York                 62.3
## 3 36005  2012 New York                 38.4
## 4 36007  2012 New York                 52.2
## 5 36009  2012 New York                 57.4
## 6 36011  2012 New York                 57.6</code></pre>
</div>
<div id="pivoting-dataframe" class="section level3">
<h3><strong>Pivoting dataframe</strong></h3>
<p><strong>pivot_longer()</strong> and <strong>pivot_wider()</strong>
are very flexible, and can easily tidy a wide variety of non-tidy
datasets</p>
<div id="pivot_wider" class="section level4">
<h4><strong>pivot_wider</strong></h4>
<p>pivot_wider() convert a dataset wider by increasing the number of
columns and decreasing the number of rows.</p>
<pre class="r"><code>LBC.wider&lt;- mf %&gt;% select (FIPS, Year, STATE, COUNTY, LBC_RATE) %&gt;%
                  pivot_wider(names_from = Year, # column need to be wider
                              values_from = LBC_RATE) # data
str(LBC.wider)</code></pre>
<pre><code>## tibble [3,107 × 18] (S3: tbl_df/tbl/data.frame)
##  $ FIPS  : num [1:3107] 1001 1003 1005 1007 1009 ...
##  $ STATE : chr [1:3107] &quot;Alabama&quot; &quot;Alabama&quot; &quot;Alabama&quot; &quot;Alabama&quot; ...
##  $ COUNTY: chr [1:3107] &quot;Autauga County&quot; &quot;Baldwin County&quot; &quot;Barbour County&quot; &quot;Bibb County&quot; ...
##  $ 1998  : num [1:3107] 90.6 72 88.3 88.3 81.3 ...
##  $ 1999  : num [1:3107] 90.4 71 89.5 89.6 81.4 ...
##  $ 2000  : num [1:3107] 89.5 70.7 90 88.6 82 ...
##  $ 2001  : num [1:3107] 89.3 71.5 91.2 89.4 81.7 ...
##  $ 2002  : num [1:3107] 89.2 70 90.9 88.8 82.2 ...
##  $ 2003  : num [1:3107] 87.3 69.5 89.2 87.6 81 ...
##  $ 2004  : num [1:3107] 85 67.2 86.3 85.3 78.8 ...
##  $ 2005  : num [1:3107] 85.6 65.4 87 86.1 78.4 ...
##  $ 2006  : num [1:3107] 84.3 65.8 85.7 85 77.5 ...
##  $ 2007  : num [1:3107] 82 64.1 83 83.3 75.4 ...
##  $ 2008  : num [1:3107] 82.1 62.1 83.2 83.8 75.8 ...
##  $ 2009  : num [1:3107] 80.1 61 83.7 83 74.3 ...
##  $ 2010  : num [1:3107] 77.8 60.5 82.9 82.1 73.8 ...
##  $ 2011  : num [1:3107] 78.1 59.8 82.4 81.9 73.8 ...
##  $ 2012  : num [1:3107] 79.6 58.5 82.3 82.1 72.8 ...</code></pre>
</div>
<div id="pivot_longer" class="section level4">
<h4><strong>pivot_longer</strong></h4>
<p>The pivot_longer() function can be used to pivot a data frame from a
wide format to a long format.</p>
<pre class="r"><code>names(LBC.wider)</code></pre>
<pre><code>##  [1] &quot;FIPS&quot;   &quot;STATE&quot;  &quot;COUNTY&quot; &quot;1998&quot;   &quot;1999&quot;   &quot;2000&quot;   &quot;2001&quot;   &quot;2002&quot;  
##  [9] &quot;2003&quot;   &quot;2004&quot;   &quot;2005&quot;   &quot;2006&quot;   &quot;2007&quot;   &quot;2008&quot;   &quot;2009&quot;   &quot;2010&quot;  
## [17] &quot;2011&quot;   &quot;2012&quot;</code></pre>
<pre class="r"><code>LBC.longer&lt;- LBC.wider %&gt;% 
              pivot_longer(cols= c(&quot;1998&quot;, &quot;1999&quot;, &quot;2000&quot;, &quot;2001&quot;, &quot;2002&quot;,
                                    &quot;2003&quot;, &quot;2004&quot;, &quot;2005&quot;, &quot;2006&quot;, &quot;2007&quot;,
                                    &quot;2008&quot;, &quot;2009&quot;, &quot;2010&quot;, &quot;2011&quot;, &quot;2012&quot;),
                          names_to = &quot;Year&quot;, # column need to be wider
                          values_to = &quot;LBC_RATE&quot;) # data
str(LBC.longer)</code></pre>
<pre><code>## tibble [46,605 × 5] (S3: tbl_df/tbl/data.frame)
##  $ FIPS    : num [1:46605] 1001 1001 1001 1001 1001 ...
##  $ STATE   : chr [1:46605] &quot;Alabama&quot; &quot;Alabama&quot; &quot;Alabama&quot; &quot;Alabama&quot; ...
##  $ COUNTY  : chr [1:46605] &quot;Autauga County&quot; &quot;Autauga County&quot; &quot;Autauga County&quot; &quot;Autauga County&quot; ...
##  $ Year    : chr [1:46605] &quot;1998&quot; &quot;1999&quot; &quot;2000&quot; &quot;2001&quot; ...
##  $ LBC_RATE: num [1:46605] 90.6 90.4 89.5 89.3 89.2 ...</code></pre>
<div style="margin-bottom:20px;">

</div>
</div>
</div>
<div id="mutate" class="section level3">
<h3><strong>Mutate</strong></h3>
<p><strong>mutate()</strong> – adds new variables while retaining old
variables to a data frame. In this exerciser, we will add log10 of LBC
rate to mf data-frame.</p>
<pre class="r"><code>mf.new&lt;- mf %&gt;% mutate(logLBC = log10(LBC_RATE))
head(mf.new[9:15])</code></pre>
<pre><code>## # A tibble: 6 × 7
##   SMOKING POVERTY  PM25   NO2   SO2 LBC_RATE logLBC
##     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
## 1    27      11.3  17.1  1.38 0.057     90.6   1.96
## 2    26      11.4  15.4  1.04 0.055     90.4   1.96
## 3    26      10.5  14.0  1.47 0.054     89.5   1.95
## 4    26.5    10.8  13.9  1.74 0.051     89.3   1.95
## 5    26.6    10.3  14.8  1.1  0.052     89.2   1.95
## 6    26.3    10.4  13.9  0.9  0.053     87.3   1.94</code></pre>
<p>Below series of codes, will create a wider datafrme of LBC mortality
rate than add three additional columns, such as Mean, Median and SD
which are represents yearly (1998-2012) mean, median and standard
deviation of LBC mortality rates. Before <strong>mutate()</strong> we
use <strong>rowwise()</strong> function which allows us to compute on a
dataframe a row-at-a-time, in our cases all 3107 counties.</p>
<pre class="r"><code>LBC.wider.summary&lt;- mf %&gt;% select (FIPS, Year, STATE, COUNTY, LBC_RATE) %&gt;%
                  pivot_wider(names_from = Year, # column need to be wider
                  values_from = LBC_RATE) %&gt;%
                  rowwise() %&gt;%
                  mutate(Mean = mean(c_across(4:18)),
                         Median= median(c_across(4:18)),
                         SD= sd(c_across(4:18))) # calculates the median 
head(LBC.wider.summary)</code></pre>
<pre><code>## # A tibble: 6 × 21
## # Rowwise: 
##    FIPS STATE   COUNTY   `1998` `1999` `2000` `2001` `2002` `2003` `2004` `2005`
##   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1  1001 Alabama Autauga…   90.6   90.4   89.5   89.3   89.2   87.3   85.0   85.6
## 2  1003 Alabama Baldwin…   72.0   71     70.7   71.5   70.0   69.5   67.2   65.4
## 3  1005 Alabama Barbour…   88.4   89.5   90.0   91.2   90.9   89.2   86.3   87.0
## 4  1007 Alabama Bibb Co…   88.4   89.6   88.6   89.4   88.8   87.6   85.3   86.1
## 5  1009 Alabama Blount …   81.3   81.4   82.0   81.7   82.2   81.0   78.8   78.4
## 6  1011 Alabama Bullock…   73.5   73.8   73.3   73.8   73.4   72.0   70.3   70.2
## # … with 10 more variables: `2006` &lt;dbl&gt;, `2007` &lt;dbl&gt;, `2008` &lt;dbl&gt;,
## #   `2009` &lt;dbl&gt;, `2010` &lt;dbl&gt;, `2011` &lt;dbl&gt;, `2012` &lt;dbl&gt;, Mean &lt;dbl&gt;,
## #   Median &lt;dbl&gt;, SD &lt;dbl&gt;</code></pre>
<div style="margin-bottom:20px;">

</div>
</div>
<div id="summarize" class="section level3">
<h3><strong>Summarize</strong></h3>
<p><strong>summarise()</strong> creates a new data frame. It will have
one (or more) rows for each combination of grouping variables; if there
are no grouping variables, the output will have a single row summarising
all observations in the input. It will contain one column for each
grouping variable and one column for each of the summary statistics that
you have specified.</p>
<p><strong>summarise()</strong> and <strong>summarize()</strong> are
synonyms.</p>
<ul>
<li><p><strong>Center</strong>: mean(), median()</p></li>
<li><p><strong>Spread</strong>: sd(), IQR(), mad()</p></li>
<li><p><strong>Range</strong>: min(), max(), quantile()</p></li>
<li><p><strong>Position</strong>: first(), last(), nth(),</p></li>
<li><p><strong>Count</strong>: n(), n_distinct()</p></li>
<li><p><strong>Logical</strong>: any(), all()</p></li>
</ul>
<pre class="r"><code># mean
summarise(mf, Mean=mean(LBC_RATE))</code></pre>
<pre><code>## # A tibble: 1 × 1
##    Mean
##   &lt;dbl&gt;
## 1  65.9</code></pre>
<pre class="r"><code># median
summarise(mf, Median=median(LBC_RATE))</code></pre>
<pre><code>## # A tibble: 1 × 1
##   Median
##    &lt;dbl&gt;
## 1   65.4</code></pre>
<div style="margin-bottom:20px;">

</div>
<p>The **scoped variants (_if, _at, _all)** of summarise() make it easy
to apply the same transformation to multiple variables. There are three
variants.</p>
<ul>
<li><p>summarise_all() affects every variable</p></li>
<li><p>summarise_at() affects variables selected with a character vector
or vars()</p></li>
<li><p>summarise_if() affects variables selected with a predicate
function</p></li>
</ul>
<p>Following series of codes create a <strong>datatable</strong> of
summary statistics of LBC_RATE, SMOKING, POVERTY, PM25, NO2, SO2
variables.</p>
<pre class="r"><code>summary_statistics &lt;- mf %&gt;% 
  # First select  numerical columns
  select(LBC_RATE, SMOKING, POVERTY, PM25, NO2, SO2) %&gt;%
  # rename LBC_rate to LBC
  dplyr::rename(&quot;LBC&quot;= LBC_RATE) %&gt;%
  # get summary statistics
   summarise_all(funs(min = min, 
                      q25 = quantile(., 0.25), 
                      median = median, 
                      q75 = quantile(., 0.75), 
                      max = max,
                      mean = mean, 
                      sd = sd)) %&gt;% 
# create a nice looking table
  pivot_longer(everything(), names_sep = &quot;_&quot;, names_to = c( &quot;variable&quot;, &quot;.value&quot;))</code></pre>
<pre><code>## Warning: `funs()` was deprecated in dplyr 0.8.0.
## ℹ Please use a list of either functions or lambdas:
## 
## # Simple named list: list(mean = mean, median = median)
## 
## # Auto named with `tibble::lst()`: tibble::lst(mean, median)
## 
## # Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
<p>We can visualize the summary_statistics using
<strong>datatable()</strong> function of <strong>DT</strong> package DT
which provides an R interface to the JavaScript library DataTables.
*datatable()** creates an HTML widget to display R data objects with
DataTables.</p>
<pre class="r"><code>datatable(as.data.frame(summary_statistics), 
          rownames = T, options = list(pageLength = 10, scrollX = TRUE, round)) %&gt;%
  formatRound(columns = 2:8, digits = 3)</code></pre>
<div id="htmlwidget-52b63661bfc7b47148fc" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-52b63661bfc7b47148fc">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6"],["LBC","SMOKING","POVERTY","PM25","NO2","SO2"],[11.18,7.1,1.7,1.04,0.06,0],[54,23.2,10.6,7.21,0.65,0.003],[65.39,25.9,13.9,9.66,1.1,0.016],[76.83,28.5,18.1,12.24,1.97,0.05],[223.6,44,62,26.05,21.56,0.632],[65.9127359725351,25.7768887458427,14.8396893037228,9.87051389335908,1.54664928655724,0.0404577620426993],[16.8038181332256,4.03719998402545,6.01448709239405,3.49528981707318,1.38791622382339,0.0640602709148616]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>variable<\/th>\n      <th>min<\/th>\n      <th>q25<\/th>\n      <th>median<\/th>\n      <th>q75<\/th>\n      <th>max<\/th>\n      <th>mean<\/th>\n      <th>sd<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"scrollX":true,"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":3,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":4,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":5,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":6,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":7,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":8,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"className":"dt-right","targets":[2,3,4,5,6,7,8]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render","options.columnDefs.2.render","options.columnDefs.3.render","options.columnDefs.4.render","options.columnDefs.5.render","options.columnDefs.6.render"],"jsHooks":[]}</script>
</div>
<div id="group-by" class="section level3">
<h3><strong>Group by</strong></h3>
<p>Now, we can apply the <strong>group_by()</strong> and
<strong>summarize()</strong> functions to calculate mean all variables
by States:</p>
<pre class="r"><code>state.mf&lt;-mf %&gt;% 
  group_by(STATE) %&gt;%
  summarize(LBC_RATE = mean(LBC_RATE),
            SMOKING = mean(SMOKING),
            POVERTY = mean(POVERTY),
            PM25 = mean(PM25),
            NO2 = mean(NO2),
            SO2 = mean(SO2))</code></pre>
<pre class="r"><code>datatable(as.data.frame(state.mf), 
          rownames = T, options = list(pageLength = 10, scrollX = TRUE, round)) %&gt;%
  formatRound(columns = 2:7, digits = 3)</code></pre>
<div id="htmlwidget-d05f112858a578a3be14" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-d05f112858a578a3be14">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49"],["Alabama","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","District of Columbia","Florida","Georgia","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],[80.1885970149254,48.1593333333333,81.6411644444444,53.8159770114943,40.9068541666667,57.22175,69.6582222222222,61.8326666666667,73.0152835820896,75.4460964360587,47.2379696969697,68.7202549019608,72.4339927536232,53.7228754208754,57.7802222222222,94.2429944444444,79.2952395833333,69.6075,65.5541388888889,59.7276666666667,64.6727710843374,51.0701455938697,77.8871869918699,73.9663652173913,57.0449761904762,51.0647240143369,67.4469019607843,61.5909333333333,59.1035873015873,44.1992323232323,62.6893440860215,68.49236,48.4707295597484,69.7529772727273,74.0105541125541,60.3034444444444,61.4104875621891,59.7357333333333,70.6724637681159,53.295158974359,82.9888421052632,61.9370341207349,33.1394712643678,60.0686666666667,69.8859899749373,57.4818974358974,81.2154181818182,55.6443333333333,51.8947536231884],[27.22,24.3906666666667,28.9349333333333,20.426091954023,21.784375,21.3216666666667,25.5777777777778,22.08,27.1291542288557,26.524821802935,22.5113636363636,25.5757516339869,28.4226811594203,24.4567003367003,23.8372063492063,32.0530555555556,28.0496875,24.5220833333333,22.6541666666667,21.5290476190476,26.2395180722892,23.7693486590038,27.3089430894309,28.9897391304348,24.2333333333333,23.1958422939068,27.2603921568627,23.6,21.7330158730159,24.3541414141414,24.0895698924731,26.5996666666667,24.44,27.8679545454545,28.6047619047619,23.8161111111111,26.0087562189055,21.772,26.8276811594203,24.76,29.1891228070175,23.8279265091864,17.6068965517241,21.8338095238095,25.3751378446115,22.6071794871795,29.9730909090909,24.8069444444444,23.7768115942029],[19.1751641791045,18.9935555555556,19.2698666666667,14.1383333333333,13.1045729166667,7.63166666666667,10.8166666666667,17.7333333333333,15.4746766169154,18.4047211740042,13.7864545454545,11.9903267973856,10.8375724637681,10.3451447811448,11.9118158730159,19.0530611111111,20.6305520833333,12.869625,9.62897222222222,9.69804761904762,13.140016064257,9.77754789272031,22.5442682926829,15.4951768115942,15.7684642857143,11.839311827957,11.3407843137255,8.44433333333333,8.50498412698413,20.2646464646465,12.6804731182796,16.0825266666667,12.8228427672956,12.1425757575758,17.0066753246753,14.266037037037,11.5203084577114,8.79413333333333,18.1760579710145,15.3214256410256,16.7422175438596,17.7503202099738,11.7941149425287,10.6624285714286,12.5991077694236,13.9184444444444,18.1206181818182,10.150462962963,10.7589275362319],[12.5080099502488,5.1752,10.9618577777778,7.4735632183908,5.29603125,9.50916666666667,13.4706666666667,13.6966666666667,9.36860696517413,12.5301467505241,5.16710606060606,13.4242483660131,14.6590072463768,10.5578585858586,8.26641904761905,12.3056055555556,10.4616041666667,6.40304166666667,12.8793611111111,8.70390476190476,9.91426506024096,8.30239846743295,11.4122357723577,10.573652173913,5.14825,7.75239426523297,4.95266666666667,7.8358,11.7626666666667,5.28937373737374,9.37690322580645,11.5263866666667,5.70562264150943,14.4459393939394,8.95693506493506,4.25481481481481,11.3216815920398,8.99226666666667,12.0691884057971,6.93122051282051,12.2349052631579,8.32144619422572,4.71813793103448,8.07171428571429,11.150335839599,5.04034188034188,11.2252,9.35141666666667,5.35124637681159],[1.12458706467662,0.446488888888889,0.885351111111111,1.71971264367816,0.577645833333333,2.54391666666667,4.09733333333333,5.584,0.860845771144279,1.31092662473795,0.460969696969697,2.55177777777778,3.27116666666667,1.22642424242424,0.873238095238095,2.32497777777778,1.16603125,0.852166666666667,3.88738888888889,3.26052380952381,2.15175903614458,1.17171647509579,0.969154471544715,1.23859130434783,0.340488095238095,0.661362007168459,0.34921568627451,1.25253333333333,5.8632380952381,0.339919191919192,3.06034408602151,1.67192,0.698805031446541,3.62630303030303,0.953922077922078,0.726,3.29722388059702,2.7504,1.3408115942029,0.511138461538462,1.79132631578947,0.872322834645669,0.611080459770115,1.17261904761905,2.21040100250627,1.2471452991453,2.56304242424242,1.66047222222222,0.348985507246377],[0.0650796019900498,0.00158666666666667,0.0183226666666667,4.59770114942529e-05,0.00184791666666667,0.0163,0.0651777777777778,0.149466666666667,0.0269203980099502,0.0605526205450734,4.39393939393939e-05,0.0681522875816993,0.113644202898551,0.00897575757575758,0.00857142857142857,0.120626111111111,0.017396875,0.00273333333333333,0.11195,0.0219761904761905,0.0242192771084337,0.00689348659003831,0.0181772357723577,0.0253130434782609,0.00265357142857143,0.00635483870967742,0.000235294117647059,0.0167266666666667,0.0488730158730159,0.00190707070707071,0.0251677419354839,0.0438873333333333,0.0142918238993711,0.144695454545455,0.0106380952380952,0.000501851851851852,0.142528358208955,0.0277733333333333,0.0344478260869565,0.00332717948717949,0.0603326315789474,0.0184031496062992,0.000774712643678161,0.00257142857142857,0.0600496240601504,0.00315726495726496,0.173467878787879,0.0153175925925926,0.00419420289855072]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>STATE<\/th>\n      <th>LBC_RATE<\/th>\n      <th>SMOKING<\/th>\n      <th>POVERTY<\/th>\n      <th>PM25<\/th>\n      <th>NO2<\/th>\n      <th>SO2<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"scrollX":true,"columnDefs":[{"targets":2,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":3,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":4,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":5,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":6,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"targets":7,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 3, 3, \",\", \".\", null);\n  }"},{"className":"dt-right","targets":[2,3,4,5,6,7]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render","options.columnDefs.2.render","options.columnDefs.3.render","options.columnDefs.4.render","options.columnDefs.5.render"],"jsHooks":[]}</script>
<div style="margin-bottom:30px;">

</div>
</div>
</div>
<div id="cleaning-a-messy-data" class="section level2">
<h2><strong>Cleaning a Messy Data</strong></h2>
<p>In this exercise you will learn how a clean data and make it ready
for analysis, such as dealing with missing values, data with below
detection limit and cleaning spatial characters. We will use data from
United States Geological Survey (USGS) as a part of the USGS Geochemical
Landscapes Project <a href="https://pubs.usgs.gov/ds/801/">(Smith et
al., 2011)</a>.</p>
<div id="load-the-data" class="section level4">
<h4>Load the data</h4>
<pre class="r"><code>## Create a data folder
dataFolder&lt;-&quot;E:/Dropbox/GitHub/chemstat-r-github.io/Data/&quot;
df.geo&lt;-read_csv(paste0(dataFolder,&quot;usa_geochemical.csv&quot;))
meta.geo&lt;-read_csv(paste0(dataFolder,&quot;usa_geochemical_meta_data.csv&quot;))</code></pre>
<pre class="r"><code>glimpse(df.geo)</code></pre>
<pre><code>## Rows: 4,857
## Columns: 56
## $ A_LabID    &lt;chr&gt; &quot;C-328943&quot;, &quot;C-328929&quot;, &quot;C-328930&quot;, &quot;C-329034&quot;, &quot;C-328968&quot;,…
## $ SiteID     &lt;dbl&gt; 96, 208, 288, 656, 912, 1232, 1312, 1488, 1680, 1824, 2144,…
## $ StateID    &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;,…
## $ Latitude   &lt;dbl&gt; 31.3146, 33.8523, 31.2179, 33.0992, 34.5501, 34.3577, 31.06…
## $ Longitude  &lt;dbl&gt; -87.1166, -86.9041, -85.8788, -86.9976, -87.6779, -87.3130,…
## $ CollDate   &lt;chr&gt; &quot;2/18/2009&quot;, &quot;2/26/2009&quot;, &quot;2/18/2009&quot;, &quot;2/23/2009&quot;, &quot;2/25/2…
## $ LandCover1 &lt;chr&gt; &quot;Planted/Cultivated&quot;, &quot;Developed&quot;, &quot;Planted/Cultivated&quot;, &quot;F…
## $ LandCover2 &lt;chr&gt; &quot;Pasture/Hay&quot;, &quot;Low Intensity Residential&quot;, &quot;Fallow&quot;, &quot;Ever…
## $ A_Depth    &lt;chr&gt; &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-5&quot;, &quot;0-10&quot;, &quot;0-25&quot;, &quot;0-3…
## $ A_Ag       &lt;chr&gt; &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;, &quot;&lt;1&quot;,…
## $ A_Al       &lt;chr&gt; &quot;0.87&quot;, &quot;1.15&quot;, &quot;1.05&quot;, &quot;4.17&quot;, &quot;1.51&quot;, &quot;2.78&quot;, &quot;2.14&quot;, &quot;1.…
## $ A_As       &lt;chr&gt; &quot;1.6&quot;, &quot;1.5&quot;, &quot;1.2&quot;, &quot;3.7&quot;, &quot;2.7&quot;, &quot;4.3&quot;, &quot;2.7&quot;, &quot;3.7&quot;, &quot;2.…
## $ A_Ba       &lt;chr&gt; &quot;49&quot;, &quot;118&quot;, &quot;34&quot;, &quot;316&quot;, &quot;179&quot;, &quot;160&quot;, &quot;50&quot;, &quot;185&quot;, &quot;77&quot;, …
## $ A_Be       &lt;chr&gt; &quot;0.2&quot;, &quot;0.4&quot;, &quot;0.2&quot;, &quot;1.1&quot;, &quot;0.6&quot;, &quot;0.5&quot;, &quot;0.3&quot;, &quot;0.5&quot;, &quot;0.…
## $ A_Bi       &lt;chr&gt; &quot;0.08&quot;, &quot;0.1&quot;, &quot;0.07&quot;, &quot;0.16&quot;, &quot;0.09&quot;, &quot;0.19&quot;, &quot;0.16&quot;, &quot;0.2…
## $ A_C_Tot    &lt;chr&gt; &quot;0.71&quot;, &quot;0.88&quot;, &quot;0.65&quot;, &quot;1.14&quot;, &quot;1.36&quot;, &quot;1.71&quot;, &quot;0.89&quot;, &quot;4.…
## $ A_C_Inorg  &lt;chr&gt; &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.…
## $ A_C_Org    &lt;chr&gt; &quot;0.71&quot;, &quot;0.88&quot;, &quot;0.65&quot;, &quot;1.14&quot;, &quot;1.36&quot;, &quot;1.71&quot;, &quot;0.89&quot;, &quot;4.…
## $ A_Ca       &lt;chr&gt; &quot;0.07&quot;, &quot;0.02&quot;, &quot;0.05&quot;, &quot;0.05&quot;, &quot;0.03&quot;, &quot;0.02&quot;, &quot;0.04&quot;, &quot;0.…
## $ A_Cd       &lt;chr&gt; &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;0.…
## $ A_Ce       &lt;chr&gt; &quot;25.2&quot;, &quot;27.8&quot;, &quot;42.2&quot;, &quot;41.7&quot;, &quot;61.7&quot;, &quot;32.6&quot;, &quot;48.6&quot;, &quot;44…
## $ A_Co       &lt;chr&gt; &quot;1.2&quot;, &quot;2.4&quot;, &quot;1&quot;, &quot;7&quot;, &quot;6.1&quot;, &quot;3.5&quot;, &quot;1.5&quot;, &quot;3.9&quot;, &quot;1.3&quot;, …
## $ A_Cr       &lt;chr&gt; &quot;11&quot;, &quot;14&quot;, &quot;8&quot;, &quot;28&quot;, &quot;17&quot;, &quot;30&quot;, &quot;17&quot;, &quot;22&quot;, &quot;22&quot;, &quot;10&quot;, …
## $ A_Cs       &lt;chr&gt; &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;, &quot;&lt;5&quot;,…
## $ A_Cu       &lt;chr&gt; &quot;4.4&quot;, &quot;6.1&quot;, &quot;10.9&quot;, &quot;13.8&quot;, &quot;5.2&quot;, &quot;8.4&quot;, &quot;15.1&quot;, &quot;10.1&quot;,…
## $ A_Fe       &lt;chr&gt; &quot;0.57&quot;, &quot;0.54&quot;, &quot;0.38&quot;, &quot;2.38&quot;, &quot;1.06&quot;, &quot;1.66&quot;, &quot;0.9&quot;, &quot;1.1…
## $ A_Ga       &lt;chr&gt; &quot;1.96&quot;, &quot;2.24&quot;, &quot;1.98&quot;, &quot;9.53&quot;, &quot;3.29&quot;, &quot;6.43&quot;, &quot;4.22&quot;, &quot;4.…
## $ A_Hg       &lt;chr&gt; &quot;0.01&quot;, &quot;0.02&quot;, &quot;&lt;0.01&quot;, &quot;0.03&quot;, &quot;0.03&quot;, &quot;0.05&quot;, &quot;0.02&quot;, &quot;0…
## $ A_In       &lt;chr&gt; &quot;&lt;0.02&quot;, &quot;&lt;0.02&quot;, &quot;&lt;0.02&quot;, &quot;0.03&quot;, &quot;&lt;0.02&quot;, &quot;0.02&quot;, &quot;&lt;0.02&quot;…
## $ A_K        &lt;chr&gt; &quot;0.09&quot;, &quot;0.25&quot;, &quot;0.05&quot;, &quot;0.89&quot;, &quot;0.44&quot;, &quot;0.46&quot;, &quot;0.1&quot;, &quot;0.3…
## $ A_La       &lt;chr&gt; &quot;11.4&quot;, &quot;13.8&quot;, &quot;23.4&quot;, &quot;20.6&quot;, &quot;21&quot;, &quot;16.3&quot;, &quot;22.3&quot;, &quot;20.9…
## $ A_Li       &lt;chr&gt; &quot;5&quot;, &quot;8&quot;, &quot;5&quot;, &quot;21&quot;, &quot;6&quot;, &quot;17&quot;, &quot;9&quot;, &quot;18&quot;, &quot;8&quot;, &quot;4&quot;, &quot;7&quot;, &quot;…
## $ A_Mg       &lt;chr&gt; &quot;0.03&quot;, &quot;0.05&quot;, &quot;0.03&quot;, &quot;0.16&quot;, &quot;0.06&quot;, &quot;0.11&quot;, &quot;0.04&quot;, &quot;0.…
## $ A_Mn       &lt;chr&gt; &quot;81&quot;, &quot;191&quot;, &quot;249&quot;, &quot;228&quot;, &quot;321&quot;, &quot;96&quot;, &quot;155&quot;, &quot;598&quot;, &quot;76&quot;,…
## $ A_Mo       &lt;chr&gt; &quot;0.34&quot;, &quot;0.36&quot;, &quot;0.41&quot;, &quot;1.19&quot;, &quot;0.48&quot;, &quot;0.66&quot;, &quot;0.76&quot;, &quot;0.…
## $ A_Na       &lt;chr&gt; &quot;&lt;0.01&quot;, &quot;0.02&quot;, &quot;&lt;0.01&quot;, &quot;0.06&quot;, &quot;0.06&quot;, &quot;0.05&quot;, &quot;&lt;0.01&quot;, …
## $ A_Nb       &lt;chr&gt; &quot;5.2&quot;, &quot;3.5&quot;, &quot;3.4&quot;, &quot;8.4&quot;, &quot;0.6&quot;, &quot;9.1&quot;, &quot;7.1&quot;, &quot;6.1&quot;, &quot;2.…
## $ A_Ni       &lt;chr&gt; &quot;3.2&quot;, &quot;4.6&quot;, &quot;4.2&quot;, &quot;11.5&quot;, &quot;6.9&quot;, &quot;8.4&quot;, &quot;7.7&quot;, &quot;7&quot;, &quot;3.8…
## $ A_P        &lt;chr&gt; &quot;260&quot;, &quot;170&quot;, &quot;510&quot;, &quot;200&quot;, &quot;200&quot;, &quot;190&quot;, &quot;680&quot;, &quot;440&quot;, &quot;10…
## $ A_Pb       &lt;chr&gt; &quot;6.8&quot;, &quot;11.6&quot;, &quot;7&quot;, &quot;14&quot;, &quot;14.5&quot;, &quot;15.4&quot;, &quot;10.5&quot;, &quot;26.6&quot;, &quot;…
## $ A_Rb       &lt;chr&gt; &quot;8.4&quot;, &quot;20&quot;, &quot;5.7&quot;, &quot;57.8&quot;, &quot;24.6&quot;, &quot;31.8&quot;, &quot;9&quot;, &quot;24.7&quot;, &quot;1…
## $ A_S        &lt;chr&gt; &quot;&lt;0.01&quot;, &quot;&lt;0.01&quot;, &quot;&lt;0.01&quot;, &quot;0.01&quot;, &quot;0.01&quot;, &quot;0.01&quot;, &quot;&lt;0.01&quot;,…
## $ A_Sb       &lt;chr&gt; &quot;0.19&quot;, &quot;0.23&quot;, &quot;0.19&quot;, &quot;0.62&quot;, &quot;0.1&quot;, &quot;0.46&quot;, &quot;0.3&quot;, &quot;0.4&quot;…
## $ A_Sc       &lt;chr&gt; &quot;1.6&quot;, &quot;1.6&quot;, &quot;1.4&quot;, &quot;7.5&quot;, &quot;2.2&quot;, &quot;4.1&quot;, &quot;3.1&quot;, &quot;2.5&quot;, &quot;3.…
## $ A_Se       &lt;chr&gt; &quot;&lt;0.2&quot;, &quot;&lt;0.2&quot;, &quot;&lt;0.2&quot;, &quot;0.5&quot;, &quot;&lt;0.2&quot;, &quot;0.4&quot;, &quot;0.2&quot;, &quot;0.4&quot;,…
## $ A_Sn       &lt;chr&gt; &quot;0.5&quot;, &quot;0.5&quot;, &quot;0.6&quot;, &quot;1.3&quot;, &quot;0.4&quot;, &quot;1&quot;, &quot;1.1&quot;, &quot;1.3&quot;, &quot;1&quot;, …
## $ A_Sr       &lt;chr&gt; &quot;6.2&quot;, &quot;15.2&quot;, &quot;3.9&quot;, &quot;30.4&quot;, &quot;21.9&quot;, &quot;27.2&quot;, &quot;6.7&quot;, &quot;27.9&quot;…
## $ A_Te       &lt;chr&gt; &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0…
## $ A_Th       &lt;chr&gt; &quot;4.4&quot;, &quot;3.2&quot;, &quot;3&quot;, &quot;8.2&quot;, &quot;5&quot;, &quot;7.1&quot;, &quot;7.2&quot;, &quot;5.9&quot;, &quot;9.2&quot;, …
## $ A_Ti       &lt;chr&gt; &quot;0.24&quot;, &quot;0.13&quot;, &quot;0.13&quot;, &quot;0.31&quot;, &quot;0.05&quot;, &quot;0.28&quot;, &quot;0.3&quot;, &quot;0.1…
## $ A_Tl       &lt;chr&gt; &quot;&lt;0.1&quot;, &quot;0.2&quot;, &quot;&lt;0.1&quot;, &quot;0.5&quot;, &quot;0.3&quot;, &quot;0.4&quot;, &quot;0.1&quot;, &quot;0.3&quot;, &quot;…
## $ A_U        &lt;chr&gt; &quot;1.4&quot;, &quot;1.1&quot;, &quot;1&quot;, &quot;2.4&quot;, &quot;1.4&quot;, &quot;2.2&quot;, &quot;2&quot;, &quot;1.9&quot;, &quot;1.9&quot;, …
## $ A_V        &lt;chr&gt; &quot;14&quot;, &quot;16&quot;, &quot;12&quot;, &quot;56&quot;, &quot;21&quot;, &quot;37&quot;, &quot;27&quot;, &quot;30&quot;, &quot;26&quot;, &quot;22&quot;,…
## $ A_W        &lt;chr&gt; &quot;0.3&quot;, &quot;0.3&quot;, &quot;0.4&quot;, &quot;0.8&quot;, &quot;&lt;0.1&quot;, &quot;0.7&quot;, &quot;0.6&quot;, &quot;0.4&quot;, &quot;&lt;…
## $ A_Y        &lt;chr&gt; &quot;3.8&quot;, &quot;4.9&quot;, &quot;16.3&quot;, &quot;8.8&quot;, &quot;8.4&quot;, &quot;6.7&quot;, &quot;9.1&quot;, &quot;9.4&quot;, &quot;5…
## $ A_Zn       &lt;chr&gt; &quot;15&quot;, &quot;17&quot;, &quot;19&quot;, &quot;32&quot;, &quot;32&quot;, &quot;28&quot;, &quot;26&quot;, &quot;48&quot;, &quot;20&quot;, &quot;34&quot;,…</code></pre>
<pre class="r"><code>glimpse(meta.geo)</code></pre>
<pre><code>## Rows: 54
## Columns: 3
## $ FIELS_ID    &lt;chr&gt; &quot;Lab_ID&quot;, &quot;SiteID&quot;, &quot;StateID&quot;, &quot;CollDate&quot;, &quot;LandCover1&quot;, &quot;…
## $ Description &lt;chr&gt; &quot;unique identifier assigned by the analytical laboratories…
## $ Unit        &lt;chr&gt; NA, NA, NA, NA, NA, NA, &quot;cm&quot;, &quot;mg/kg&quot;, &quot;wt. %&quot;, &quot;mg/kg&quot;, &quot;…</code></pre>
<p>We first create a file with limited number of variables using
<strong>select</strong> functions</p>
<pre class="r"><code>mf.geo &lt;- df.geo %&gt;%
      select(A_LabID, StateID,  LandCover1, A_Depth, A_C_Tot, A_C_Inorg, A_C_Org, A_As, A_Cd,  A_Pb, A_Cr) %&gt;%
      rename(&quot;LAB_ID&quot;=A_LabID,
             &quot;LandCover&quot; =LandCover1,
             &quot;Soil_depth&quot; = A_Depth,
             &quot;Total_Carbon&quot; = A_C_Tot,
             &quot;Inorg_Carbon&quot; = A_C_Inorg,
             &quot;Organic_Carbon&quot;= A_C_Org, 
             &quot;Arsenic&quot; = A_As,
             &quot;Cadmium&quot; = A_Cd,
             &quot;Lead&quot; = A_Pb,
             &quot;Chromium&quot; = A_Cr) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 4,857
## Columns: 11
## $ LAB_ID         &lt;chr&gt; &quot;C-328943&quot;, &quot;C-328929&quot;, &quot;C-328930&quot;, &quot;C-329034&quot;, &quot;C-3289…
## $ StateID        &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;…
## $ LandCover      &lt;chr&gt; &quot;Planted/Cultivated&quot;, &quot;Developed&quot;, &quot;Planted/Cultivated&quot;…
## $ Soil_depth     &lt;chr&gt; &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-5&quot;, &quot;0-10&quot;, &quot;0-25&quot;, …
## $ Total_Carbon   &lt;chr&gt; &quot;0.71&quot;, &quot;0.88&quot;, &quot;0.65&quot;, &quot;1.14&quot;, &quot;1.36&quot;, &quot;1.71&quot;, &quot;0.89&quot;,…
## $ Inorg_Carbon   &lt;chr&gt; &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;, &quot;N.D.&quot;,…
## $ Organic_Carbon &lt;chr&gt; &quot;0.71&quot;, &quot;0.88&quot;, &quot;0.65&quot;, &quot;1.14&quot;, &quot;1.36&quot;, &quot;1.71&quot;, &quot;0.89&quot;,…
## $ Arsenic        &lt;chr&gt; &quot;1.6&quot;, &quot;1.5&quot;, &quot;1.2&quot;, &quot;3.7&quot;, &quot;2.7&quot;, &quot;4.3&quot;, &quot;2.7&quot;, &quot;3.7&quot;,…
## $ Cadmium        &lt;chr&gt; &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;, &quot;&lt;0.1&quot;,…
## $ Lead           &lt;chr&gt; &quot;6.8&quot;, &quot;11.6&quot;, &quot;7&quot;, &quot;14&quot;, &quot;14.5&quot;, &quot;15.4&quot;, &quot;10.5&quot;, &quot;26.6…
## $ Chromium       &lt;chr&gt; &quot;11&quot;, &quot;14&quot;, &quot;8&quot;, &quot;28&quot;, &quot;17&quot;, &quot;30&quot;, &quot;17&quot;, &quot;22&quot;, &quot;22&quot;, &quot;1…</code></pre>
<p>Now, we filter the data where records have N.S. values INS:</p>
<pre class="r"><code>mf.geo&lt;- mf.geo %&gt;% 
        filter(Soil_depth != &quot;N.S.&quot; &amp; Total_Carbon !=&quot;INS&quot;)</code></pre>
<p>Then, we will convert all N.D. values to empty string:</p>
<pre class="r"><code>mf.geo[mf.geo==&quot;N.D.&quot;]&lt;- &quot;&quot;</code></pre>
<p>Here detection limits of As, Cd, Pb and Cr are 0.6, 0.1, 0.5, and 1
mg/kg, respectively. We will replace the values below detection limits
by half of detection limits of these heavy-metals. Before that we have
to remove <strong>“&lt;”</strong> and convert the all
<strong><chr></strong> to <strong><double></strong>.</p>
<pre class="r"><code>mf.geo &lt;- mf.geo %&gt;%
      mutate_at(c(&quot;Arsenic&quot;, &quot;Cadmium&quot;, &quot;Lead&quot;, &quot;Chromium&quot;), str_replace, &quot;&lt;&quot;, &quot;&quot;) %&gt;%
      mutate_at(c(5:11), as.numeric) %&gt;% glimpse()</code></pre>
<pre><code>## Warning in mask$eval_all_mutate(quo): NAs introduced by coercion

## Warning in mask$eval_all_mutate(quo): NAs introduced by coercion</code></pre>
<pre><code>## Rows: 4,809
## Columns: 11
## $ LAB_ID         &lt;chr&gt; &quot;C-328943&quot;, &quot;C-328929&quot;, &quot;C-328930&quot;, &quot;C-329034&quot;, &quot;C-3289…
## $ StateID        &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;…
## $ LandCover      &lt;chr&gt; &quot;Planted/Cultivated&quot;, &quot;Developed&quot;, &quot;Planted/Cultivated&quot;…
## $ Soil_depth     &lt;chr&gt; &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-5&quot;, &quot;0-10&quot;, &quot;0-25&quot;, …
## $ Total_Carbon   &lt;dbl&gt; 0.71, 0.88, 0.65, 1.14, 1.36, 1.71, 0.89, 4.59, 2.32, 0…
## $ Inorg_Carbon   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
## $ Organic_Carbon &lt;dbl&gt; 0.71, 0.88, 0.65, 1.14, 1.36, 1.71, 0.89, 4.59, 2.32, 0…
## $ Arsenic        &lt;dbl&gt; 1.6, 1.5, 1.2, 3.7, 2.7, 4.3, 2.7, 3.7, 2.9, 3.0, 2.3, …
## $ Cadmium        &lt;dbl&gt; 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, …
## $ Lead           &lt;dbl&gt; 6.8, 11.6, 7.0, 14.0, 14.5, 15.4, 10.5, 26.6, 13.2, 12.…
## $ Chromium       &lt;dbl&gt; 11, 14, 8, 28, 17, 30, 17, 22, 22, 10, 17, 10, 31, 11, …</code></pre>
<p>Now replace values below detection limits:</p>
<pre class="r"><code>mf.geo[&quot;Arsenic&quot;][mf.geo[&quot;Arsenic&quot;] == 0.6] &lt;- 0.3
mf.geo[&quot;Cadmium&quot;][mf.geo[&quot;Cadmium&quot;] == 0.1] &lt;- 0.05
mf.geo[&quot;Lead&quot;][mf.geo[&quot;Lead&quot;] == 0.5] &lt;- 0.25
mf.geo[&quot;Chromium&quot;][mf.geo[&quot;Chromium&quot;] == 1] &lt;- 0.5</code></pre>
<p>Now will check the missing values of the data:</p>
<pre class="r"><code># counting unique, missing, and median values
Arsenic&lt;- mf.geo %&gt;% summarise(N = length(Arsenic),
                 na = sum(is.na(Arsenic)),
                 Min = min(Arsenic, na.rm = TRUE),
                 Max =max(Arsenic, na.rm = TRUE))

Cadmium&lt;- mf.geo %&gt;% summarise(N = length(Cadmium),
                 na = sum(is.na(Cadmium)),
                 Min = min(Cadmium, na.rm = TRUE),
                 Max =max(Cadmium, na.rm = TRUE))

Lead&lt;- mf.geo %&gt;% summarise(N = length(Lead),
                 na = sum(is.na(Lead)),
                 Min = min(Lead, na.rm = TRUE),
                 Max =max(Lead, na.rm = TRUE))

Chromium&lt;- mf.geo %&gt;% summarise(N = length(Chromium),
                 na = sum(is.na(Chromium)),
                 Min = min(Chromium, na.rm = TRUE),
                 Max =max(Chromium, na.rm = TRUE),
                 )

#bind the data
geo.sum&lt;- bind_rows(Arsenic, Cadmium, Lead, Chromium)

#add.row.names
row.names(geo.sum) &lt;- c(&quot;Arsenic&quot;, &quot;Cadmium&quot;, &quot;Lead&quot;, &quot;Chromium&quot;)</code></pre>
<pre><code>## Warning: Setting row names on a tibble is deprecated.</code></pre>
<pre class="r"><code>datatable(geo.sum)</code></pre>
<div id="htmlwidget-243ee26a693b92e29143" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-243ee26a693b92e29143">{"x":{"filter":"none","vertical":false,"data":[["Arsenic","Cadmium","Lead","Chromium"],[4809,4809,4809,4809],[0,0,0,0],[0.3,0.05,0.25,0.5],[1110,46.6,2200,3850]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>N<\/th>\n      <th>na<\/th>\n      <th>Min<\/th>\n      <th>Max<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>One of the common method of replacing missing values is
<strong>na.omit</strong>. The function <strong>na.omit()</strong>
returns the object with listwise deletion of missing values and function
create new dataset without missing data.</p>
<pre class="r"><code>newdata &lt;- na.omit(mf.geo)
glimpse(newdata)</code></pre>
<pre><code>## Rows: 1,167
## Columns: 11
## $ LAB_ID         &lt;chr&gt; &quot;C-329044&quot;, &quot;C-329030&quot;, &quot;C-329081&quot;, &quot;C-329079&quot;, &quot;C-3289…
## $ StateID        &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AR&quot;, &quot;AR&quot;, &quot;AZ&quot;, &quot;AZ&quot;, &quot;…
## $ LandCover      &lt;chr&gt; &quot;Planted/Cultivated&quot;, &quot;Developed&quot;, &quot;Planted/Cultivated&quot;…
## $ Soil_depth     &lt;chr&gt; &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-15&quot;, &quot;0-7&quot;, &quot;0-20&quot;, &quot;0-10&quot;, &quot;0-5&quot;, &quot;…
## $ Total_Carbon   &lt;dbl&gt; 2.90, 4.78, 0.75, 1.69, 1.00, 1.00, 1.88, 0.31, 2.13, 0…
## $ Inorg_Carbon   &lt;dbl&gt; 1.8, 3.7, 0.1, 0.1, 0.2, 0.1, 0.1, 0.2, 0.9, 0.4, 0.1, …
## $ Organic_Carbon &lt;dbl&gt; 1.1, 1.1, 0.7, 1.6, 0.8, 0.9, 1.8, 0.1, 1.2, 0.3, 0.8, …
## $ Arsenic        &lt;dbl&gt; 5.9, 7.9, 5.6, 7.2, 2.9, 4.8, 1.9, 5.3, 4.5, 5.0, 4.0, …
## $ Cadmium        &lt;dbl&gt; 0.20, 0.20, 0.05, 0.20, 0.05, 0.05, 0.05, 0.20, 0.20, 0…
## $ Lead           &lt;dbl&gt; 20.9, 19.1, 12.9, 21.1, 14.1, 11.9, 8.7, 26.8, 14.7, 24…
## $ Chromium       &lt;dbl&gt; 73, 68, 37, 42, 36, 31, 16, 36, 35, 28, 30, 25, 62, 21,…</code></pre>
<p>This function delete all records with missing values. Now newdata
have only 1,167 records, since Inorg_Carbon variable has 3,690 missing
values which all are omitted.</p>
<p>We can impute missing values in several ways. The easiest way to
impute missing values is by replacing the mean values of the variable.
The following code replace missing of Arsenic, Cadmium, Lead and
Chromium with their mean values.</p>
<pre class="r"><code>mf.geo.new&lt;-mf.geo %&gt;% mutate_at(vars(Arsenic, Cadmium, Lead, Chromium),~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x)) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 4,809
## Columns: 11
## $ LAB_ID         &lt;chr&gt; &quot;C-328943&quot;, &quot;C-328929&quot;, &quot;C-328930&quot;, &quot;C-329034&quot;, &quot;C-3289…
## $ StateID        &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;…
## $ LandCover      &lt;chr&gt; &quot;Planted/Cultivated&quot;, &quot;Developed&quot;, &quot;Planted/Cultivated&quot;…
## $ Soil_depth     &lt;chr&gt; &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-20&quot;, &quot;0-5&quot;, &quot;0-10&quot;, &quot;0-25&quot;, …
## $ Total_Carbon   &lt;dbl&gt; 0.71, 0.88, 0.65, 1.14, 1.36, 1.71, 0.89, 4.59, 2.32, 0…
## $ Inorg_Carbon   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
## $ Organic_Carbon &lt;dbl&gt; 0.71, 0.88, 0.65, 1.14, 1.36, 1.71, 0.89, 4.59, 2.32, 0…
## $ Arsenic        &lt;dbl&gt; 1.6, 1.5, 1.2, 3.7, 2.7, 4.3, 2.7, 3.7, 2.9, 3.0, 2.3, …
## $ Cadmium        &lt;dbl&gt; 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.20, 0.05, 0…
## $ Lead           &lt;dbl&gt; 6.8, 11.6, 7.0, 14.0, 14.5, 15.4, 10.5, 26.6, 13.2, 12.…
## $ Chromium       &lt;dbl&gt; 11, 14, 8, 28, 17, 30, 17, 22, 22, 10, 17, 10, 31, 11, …</code></pre>
<pre class="r"><code>mf.geo.new %&gt;% summarise(sum(is.na(Chromium)))</code></pre>
<pre><code>## # A tibble: 1 × 1
##   `sum(is.na(Chromium))`
##                    &lt;int&gt;
## 1                      0</code></pre>
<div style="margin-bottom:40px;">

</div>
</div>
</div>
<div id="further-reading" class="section level2">
<h2><strong>Further Reading</strong></h2>
<ol style="list-style-type: decimal">
<li><p><a href="https://r4ds.had.co.nz/">R for Data Science</a></p></li>
<li><p><a href="https://cengel.github.io/R-data-wrangling/">Data
Wrangling with R</a></p></li>
<li><p><a
href="https://link.springer.com/book/10.1007/978-3-319-45599-0">Book:
Data Wrangling with R</a></p></li>
<li><p><a
href="https://github.com/rstudio/webinars/blob/master/05-Data-Wrangling-with-R-and-RStudio/wrangling-webinar.pdf">PDF
Data wrangling with R and RStudio</a></p></li>
<li><p><a href="https://www.youtube.com/watch?v=CnY5Y5ANnjE">Youtube
Data Wrangling with R and the Tidyverse - Workshop</a></p></li>
</ol>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
